### PR TITLE
Confirm imageconvert

### LINKED ISSUE #130: Two part translation not working correctly
At least this translation, that is split into two parts is not working as it is supposed to. The ´{0}´ is supposed to be the name of the image, that is going to be processed.

translation_error

This is in **Scene / Images... / View Details... / Convert to local** that is used on linked images. Can't say what is wrong yet but should probably double check the other similar cases too.

### PR DESCRIPTION
**Pull request by peteihis**
Resolves #130

### CODE REVIEW

File: ArtOfIllusion/src/artofillusion/image/ImageDetailsDialog.java [hunk 1]
```diff
@@ -318,7 +318,7 @@ private void convertToLocal()
             return;
 
         String name = im.getName();
-        if (name.isEmpty());
+        if (name.isEmpty())
```
Comment (makiam) [inline ArtOfIllusion/src/artofillusion/image/ImageDetailsDialog.java]: BTW... This is a good example that no-brace code style is no good

Comment (peteihis) [reply ArtOfIllusion/src/artofillusion/image/ImageDetailsDialog.java]: I fail to see the connection. It happens just as well with or without braces.

**Comment by Sailsman63** [comment]
Good catch!
